import img1 from '../assets/monkeys/1.jpg';
import img2 from '../assets/monkeys/2.jpg';
import img3 from '../assets/monkeys/3.jpg';
import img4 from '../assets/monkeys/4.jpg';
import img5 from '../assets/monkeys/5.jpg';
import img6 from '../assets/monkeys/6.jpg';
import img7 from '../assets/monkeys/7.jpg';
import img8 from '../assets/monkeys/8.jpg';
import img9 from '../assets/monkeys/9.jpg';
import img10 from '../assets/monkeys/10.jpg';
import img11 from '../assets/monkeys/11.jpg';
import img12 from '../assets/monkeys/12.jpg';
import img13 from '../assets/monkeys/13.jpg';
import img14 from '../assets/monkeys/14.jpg';
import img15 from '../assets/monkeys/15.jpg';
import img16 from '../assets/monkeys/16.jpg';
import img17 from '../assets/monkeys/17.jpg';
import img18 from '../assets/monkeys/18.jpg';
import img19 from '../assets/monkeys/19.jpg';
import img20 from '../assets/monkeys/20.jpg';
import img21 from '../assets/monkeys/21.jpg';
import img22 from '../assets/monkeys/22.jpg';
import img23 from '../assets/monkeys/23.jpg';
import img24 from '../assets/monkeys/24.jpg';

export {img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24};